Turbopack: fix source map panic (#81212)
Fix a panic, related to scope hoisting.
```
An error occurred while generating the chunk item X
Caused by:
- Cannot decode dummy BytePos
```

```
thread 'tokio-runtime-worker' panicked at turbopack/crates/turbopack-ecmascript/src/lib.rs:2431:13:
Cannot decode dummy BytePos
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/59aa1e873028948faaf8b97e5e02d4db340ad7b1/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/59aa1e873028948faaf8b97e5e02d4db340ad7b1/library/core/src/panicking.rs:75:14
   2: <turbopack_ecmascript::CodeGenResultComments>::decode_bytepos
             at next.js/turbopack/crates/turbopack-ecmascript/src/lib.rs:2431:13
   3: <turbopack_ecmascript::CodeGenResultCommentsConsumable as swc_common::comments::Comments>::has_leading
             at next.js/turbopack/crates/turbopack-ecmascript/src/lib.rs:2499:21
   4: <swc_ecma_codegen::Emitter<swc_ecma_codegen::text_writer::basic_impl::JsWriter<&mut alloc::vec::Vec<u8>>, turbopack_ecmascript::CodeGenResultSourceMap>>::has_leading_comment
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swc_ecma_codegen-15.0.1/src/lib.rs:839:24
   5: <swc_ecma_codegen::Emitter<swc_ecma_codegen::text_writer::basic_impl::JsWriter<&mut alloc::vec::Vec<u8>>, turbopack_ecmascript::CodeGenResultSourceMap>>::has_leading_comment
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swc_ecma_codegen-15.0.1/src/lib.rs:830:29
```