Sync NFT test suite from upstream (#81189)
Prompted by https://github.com/vercel/next.js/pull/81186


zeromq fails with:
```
2025-07-02T18:18:18.6796394Z         FAIL [   2.187s] turbopack::node-file-trace node_file_trace_noop_backing_storage::case_109_zeromq
Error: Failed to load zeromq.js addon.node: Error: ENOENT: no such file or directory,
open '/private/var/folders/s5/952zt8mn6ms05__7r749hkjm0000gn/T/tests_output/persistent_cache_node-file-trace/integration/zeromq.js/tests/node-file-trace/node_modules/.pnpm/zeromq@6.4.2/node_modules/zeromq/build/manifest.json'
```
probably because of `__importDefault` here
```js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
const fs_1 = __importDefault(require("fs"));
const path_1 = __importDefault(require("path"));
const manifest = JSON.parse(fs_1.default.readFileSync(path_1.default.resolve(buildDir, "manifest.json"), "utf-8"));
```
Created PACK-4987 to track that